repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.5.0
        hooks:
        -   id: double-quote-string-fixer
        -   id: end-of-file-fixer
        -   id: fix-encoding-pragma
        -   id: mixed-line-ending
        -   id: trailing-whitespace

    -   repo: https://github.com/ikamensh/flynt/
        rev: '0.55'
        hooks:
        -   id: flynt
            args: [
                '--line-length=120',
                '--fail-on-change',
            ]

    -   repo: https://github.com/pycqa/isort
        rev: 5.9.3
        hooks:
        -   id: isort

    -   repo: https://github.com/pre-commit/mirrors-yapf
        rev: v0.31.0
        hooks:
        -   id: yapf
            name: yapf
            types: [python]
            args: ['-i']
            additional_dependencies:
            -   toml

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.910
        hooks:
        -   id: mypy
            additional_dependencies:
            -   typing-extensions
            files: ^(biblary/.*py)$

    -   repo: https://github.com/PyCQA/pylint
        rev: v2.11.1
        hooks:
        -   id: pylint
            language: system

    -   repo: https://github.com/PyCQA/pydocstyle
        rev: 5.0.2
        hooks:
        -   id: pydocstyle
            args: ['--ignore=D104,D203,D213']
